apiVersion: apps/v1
kind: Deployment
metadata:
  name: juice-shop
  namespace: default
  labels:
    app: juice-shop
spec:
  replicas: 3
  selector:
    matchLabels:
      app: juice-shop
  template:
    metadata:
      labels:
        app: juice-shop
    spec:
      containers:
      - name: juice-shop
        image: bkimminich/juice-shop
        ports:
        - containerPort: 3000

---
apiVersion: v1
kind: Service
metadata:
  name: juice-shop
  namespace: default
spec:
  type: ClusterIP
  selector:
    app: juice-shop
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: juice-shop
  namespace: default
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  ingressClassName: "nginx"
  rules:
  - host: "juice-shop.example.com"
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: juice-shop
            port:
              number: 3000

